### ISSUE TITLE
[Chore] Create dummy data model and add to a table on db

### ISSUE THREAD

**Issue by riccjohn** [riccjohn/junk4dollars-api#4]
# Tasks
- [ ] Write tests for a dummy data model
- [ ] Create dummy model
- [ ] Populate test db with data to be used for testing
- [ ] Update controller so it actually responds with data from the database instead of a hard-coded response
